//Shopping cart
export const ADD_SHOPPING_CART = "ADD_SHOPPING_CART";
export const DELETE_SHOPPING_CART = "DELETE_SHOPPING_CART";

//Books
export const INITIALIZATION_BOOKS = "INITIALIZATION_BOOKS";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

//authors
export const ADD_AUTHOR_FILTER = "ADD_AUTHOR_FILTER";
export const REMOVE_AUTHOR_FILTER = "REMOVE_AUTHOR_FILTER";

//publishers
export const ADD_PUBLISHER_FILTER = "ADD_PUBLISHER_FILTER";
export const REMOVE_PUBLISHER_FILTER = "REMOVE_PUBLISHER_FILTER";

//cateroies
export const ADD_CATEGORY_FILTER = "ADD_CATEGORY_FILTER";
export const REMOVE_CATEGORY_FILTER = "REMOVE_CATEGORY_FILTER";

//prices
export const SET_MIN_RPICE = "SET_MIN_RPICE";
export const SET_MAX_PRICE = "SET_MAX_PRICE";

//search
export const SET_KEYWORD = "SET_KEYWORD";

//users
export const SET_USER = "SET_USER";
export const SIGN_OUT = "SIGN_OUT";
